version: "3.7"

services:
    web:
        container_name: djcook_web
        image: v1
        build:
            context: "."
            dockerfile: Dockerfile
        environment:
            - SECRET_KEY=${SECRET_KEY}
            - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
            - DB_NAME=${DB_NAME}
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
            - DJANGO_SETTINGS_MODULE=config.settings.prod
        command: gunicorn config.wsgi.py:application --bind 0.0.0.0:8000 --log-file logs/gunicorn-error.log
        volumes:
            - .:/app
            - ./static:/app/static/
        depends_on:
            - db
        ports:
            - "8000:8000"
        restart: always
    bot:
        container_name: djcook_bot
        image: jeromepacman:1
        environment:
            - SECRET_KEY=${SECRET_KEY}
            - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
            - DB_NAME=${DB_NAME}
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
            - DJANGO_SETTINGS_MODULE= djcook.prod_settings
        command: python3 manage.py runbot
        depends_on:
            - web
        restart: always
    db:
        image: postgres:13
        container_name: djcook_db
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        volumes:
            - ./data:/var/lib/postgresql/data
        restart: always
volumes:
    static_volume:
    postgres_data:
