# Generated by Django 3.2.10 on 2021-12-17 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_botuser_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='joined',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
