# Generated by Django 4.0 on 2021-12-10 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_botuser_chat_id_alter_botuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='chat_id',
            field=models.CharField(max_length=64),
        ),
    ]
