# Generated by Django 4.0 on 2021-12-10 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_botuser_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='chat_id',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
