# Generated by Django 4.0 on 2021-12-10 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_alter_botuser_chat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botuser',
            name='id',
        ),
        migrations.AlterField(
            model_name='botuser',
            name='chat_id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
